defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "{step}-{epoch}-{val_loss:.4f}-{test_loss:.4f}-{train_per_step:.4f}"
  monitor: "val_loss"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False
  every_n_epochs: 1 # save_interval: 1
  save_top_k: 10
  

early_stopping:
  monitor: "val_loss" # both regression task
  patience: 150       # ANI1: 500, MD17: 300, PCQM4MV2: 150, QM9-FT: 1500, QM9: 1500
  mode: "min"

model_summary:
  max_depth: -1
