# @package _global_

defaults:
  - _self_
  - data: QM9 # choose datamodule with `test_dataloader()` for evaluation
  - model: QM9
  - logger: csv
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: logs/train/runs/2025-09-15_10-58-46/checkpoints/last.ckpt
